### ISSUE TITLE
English support,Please

### ISSUE THREAD

**Issue by dongshengfengniaowu** [securedevteam/Security-Doors#28]

**Comment by MikhailMasny** [comment]
@dongshengfengniaowu Thanks for the question! Due to the high workload of our developers, in the near future we will not be able to implement this. However, within 1 month we will definitely add this. You can follow our project by subscribing to it.

Best regards, Mikhail M.

**Comment by MikhailMasny** [comment]
@dongshengfengniaowu Hello! English support has been successfully added to the project.

Best regards, Mikhail M.
